### ISSUE TITLE
include ability to handle multiple languages in tests.yml

### ISSUE THREAD

**Issue by trevorcampbell** [UBC-DSCI/autotest#22]
Right now, as long as all assignments in the course use one language, our current `tests.yml` file should work fine. But if we have multiple languages in one course, the way it's structured now will cause problems.

We should include some syntax in the `tests.yml` file that specifies language name. So in particular:

```
python:
    setup: "blahblah"
    success: "blahblah"
    templates:
        default:
            "Blah"
R:
    setup: "blah"
    etc
````
